---
- name: Configurar servidor de aplicação Java
  hosts: app01

  user: vagrant
  become: true

  vars:
    dbhost: "db01"
    dbname: "notes"
    dbusername: "notesapp"
    dbpassword: "senha123"
    notes_path: "/opt/notes"
  tasks:
    - name: Adicionar usuario de app
      user:
        name: app
        comment: Usuario de aplicação
        uid: 500
    - name: Instalação do Maven
      dnf:
        name: maven
        state: latest
    - name: Instalação do Java
      dnf:
        name: java-1.8.0-openjdk
        state: latest
    - name: Criação do diretório de app
      file:
        path: "{{ notes_path }}"
        state: directory
        owner: app
        group: app
    - name: instalacao do git client
      dnf:
        name: git
        state: latest
    - name: Clone do repositório Notes - app
      git:
        repo: 'https://github.com/callicoder/spring-boot-mysql-rest-api-tutorial.git'
        dest: "{{ notes_path }}"
        clone: yes
        force: yes
      become_user: app
    - name: Configurar arquivo de propriedades para camada de banco de dados
      template:
        src: application.properties
        dest: "{{ notes_path }}/src/main/resources/application.properties"
    - name: Gerar pacote da aplicação
      shell: mvn clean package -DskipTests
      args:
        chdir: "{{ notes_path }}"
      become_user: app
    - name: Registrar versao atual do pacote
      shell:
        cmd: mvn org.apache.maven.plugins:maven-help-plugin:2.1.1:evaluate -Dexpression=project.version | grep -v '\['
        chdir: "{{ notes_path }}"
      register: app_version
    - name: Configurar serviço do Systemd
      template:
        src: etc/systemd/system/notes.service
        dest: /etc/systemd/system/notes.service
      notify: reload daemon
    - name: Iniciar serviço notes
      service:
        name: notes
        state: restarted
        enabled: yes
  roles:
      - configuracao-default-so
  handlers:
    - name: reload app
      systemd:
        state: restarted
        daemon_reload: yes
        name: 'notes'
    - name: reload daemon
      systemd:
        daemon_reexec: yes