---
- name: Configurar servidor banco de dados
  hosts: db01
  user: vagrant
  become: true
  vars_files:
    - vars/main.yml
  vars:
    dbname: "db01"
    dbusername: "root"
    dbpassword: "senha123"
  roles:
    - configuracao-default-so
    - role: geerlingguy.mysql
