Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream9"
  config.vbguest.installer_options = { allow_kernel_upgrade: true }
  config.vm.hostname = "control-node"
  config.vm.network "private_network", ip: "192.168.1.2"
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.provider "virtualbox" do |vb, override|
    if Vagrant::Util::Platform.windows?
      override.vm.synced_folder ".", "/vagrant", type: "rsync"
    end
  end
  config.vm.provision "shell", path: "provision.sh"
end
