mysql_root_password: senha123
mysql_databases:
  - name: notes
    encoding: latin1
    collation: latin1_general_ci
mysql_users:
  - name: notesapp
    host: "%"
    password: senha123
    priv: "notes.*:ALL"