# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|

  config.vm.define "my_cent_os_box" do |c|
    c.vm.box = "centos/7"
    c.vbguest.installer_options = { allow_kernel_upgrade: true }

    c.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: '127.0.0.1'
    c.vm.provision "shell", path: "provision.sh"
  end

end

