Vagrant.configure("2") do |config|
  config.vm.box = "centos/stream9"
  config.vm.hostname = "db01"

  # Rede privada e porta exposta
  config.vm.network "private_network", ip: "192.168.1.4"
  config.vm.network "forwarded_port", guest: 3306, host: 3306

  # Recomendado: desativar pasta partilhada se Guest Additions falhar
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Ativa o plugin vbguest se estiver instalado
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = true
    config.vbguest.installer_options = { allow_kernel_upgrade: true }
  end

  # Script de provisionamento
  config.vm.provision "shell", path: "provision.sh"
end
